/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Snapshot of the names shipped by the quasar@2.27.0 and
 * @quasar/extras@2.0.4 packages installed in this repository.
 * Regenerate with: `node scripts/generate-quasar-lists.mjs`.
 *
 * Derived data only. Project policy (Pro exclusions, deprecated language
 * aliases, 'all' semantics) and curated sets (the supported plugin list,
 * the utility/composable import selection) stay in the handwritten
 * `src/internal/*.ts` modules and are never edited by the generator.
 */
/** General animations from @quasar/extras animate-list.js. */
export const GENERATED_GENERAL_ANIMATIONS = [
  'bounce',
  'flash',
  'flip',
  'headShake',
  'heartBeat',
  'hinge',
  'jello',
  'pulse',
  'rubberBand',
  'shake',
  'shakeX',
  'shakeY',
  'swing',
  'tada',
  'wobble',
] as const

/** In animations from @quasar/extras animate-list.js. */
export const GENERATED_IN_ANIMATIONS = [
  'backInDown',
  'backInLeft',
  'backInRight',
  'backInUp',
  'bounceIn',
  'bounceInDown',
  'bounceInLeft',
  'bounceInRight',
  'bounceInUp',
  'fadeIn',
  'fadeInBottomLeft',
  'fadeInBottomRight',
  'fadeInDown',
  'fadeInDownBig',
  'fadeInLeft',
  'fadeInLeftBig',
  'fadeInRight',
  'fadeInRightBig',
  'fadeInTopLeft',
  'fadeInTopRight',
  'fadeInUp',
  'fadeInUpBig',
  'flipInX',
  'flipInY',
  'jackInTheBox',
  'lightSpeedInLeft',
  'lightSpeedInRight',
  'rollIn',
  'rotateIn',
  'rotateInDownLeft',
  'rotateInDownRight',
  'rotateInUpLeft',
  'rotateInUpRight',
  'slideInDown',
  'slideInLeft',
  'slideInRight',
  'slideInUp',
  'zoomIn',
  'zoomInDown',
  'zoomInLeft',
  'zoomInRight',
  'zoomInUp',
] as const

/** Out animations from @quasar/extras animate-list.js. */
export const GENERATED_OUT_ANIMATIONS = [
  'backOutDown',
  'backOutLeft',
  'backOutRight',
  'backOutUp',
  'bounceOut',
  'bounceOutDown',
  'bounceOutLeft',
  'bounceOutRight',
  'bounceOutUp',
  'fadeOut',
  'fadeOutBottomLeft',
  'fadeOutBottomRight',
  'fadeOutDown',
  'fadeOutDownBig',
  'fadeOutLeft',
  'fadeOutLeftBig',
  'fadeOutRight',
  'fadeOutRightBig',
  'fadeOutTopLeft',
  'fadeOutTopRight',
  'fadeOutUp',
  'fadeOutUpBig',
  'flipOutX',
  'flipOutY',
  'lightSpeedOutLeft',
  'lightSpeedOutRight',
  'rollOut',
  'rotateOut',
  'rotateOutDownLeft',
  'rotateOutDownRight',
  'rotateOutUpLeft',
  'rotateOutUpRight',
  'slideOutDown',
  'slideOutLeft',
  'slideOutRight',
  'slideOutUp',
  'zoomOut',
  'zoomOutDown',
  'zoomOutLeft',
  'zoomOutRight',
  'zoomOutUp',
] as const

/** Animate css files with no animate-list.js group entry. */
export const GENERATED_ORPHAN_ANIMATIONS = [
  'lightSpeedIn',
  'lightSpeedOut',
] as const

/** Every quasar/icon-set/*.js mapping, including policy-excluded variants. */
export const GENERATED_ICON_SETS_SHIPPED = [
  'bootstrap-icons',
  'eva-icons',
  'fontawesome-v5',
  'fontawesome-v5-pro',
  'fontawesome-v6',
  'fontawesome-v6-pro',
  'fontawesome-v7',
  'fontawesome-v7-pro',
  'ionicons-v4',
  'line-awesome',
  'material-icons',
  'material-icons-outlined',
  'material-icons-round',
  'material-icons-sharp',
  'material-symbols-outlined',
  'material-symbols-rounded',
  'material-symbols-sharp',
  'mdi-v3',
  'mdi-v4',
  'mdi-v5',
  'mdi-v6',
  'mdi-v7',
  'svg-bootstrap-icons',
  'svg-eva-icons',
  'svg-fontawesome-v5',
  'svg-fontawesome-v6',
  'svg-fontawesome-v7',
  'svg-ionicons-v4',
  'svg-ionicons-v5',
  'svg-ionicons-v6',
  'svg-ionicons-v7',
  'svg-ionicons-v8',
  'svg-line-awesome',
  'svg-material-icons',
  'svg-material-icons-outlined',
  'svg-material-icons-round',
  'svg-material-icons-sharp',
  'svg-material-symbols-outlined',
  'svg-material-symbols-rounded',
  'svg-material-symbols-sharp',
  'svg-mdi-v6',
  'svg-mdi-v7',
  'svg-themify',
  'themify',
] as const

/** Every @quasar/extras export dir bundling a same-named css file. */
export const GENERATED_ICON_LIBRARIES_SHIPPED = [
  'bootstrap-icons',
  'eva-icons',
  'fontawesome-v7',
  'ionicons-v4',
  'line-awesome',
  'material-icons',
  'material-icons-outlined',
  'material-icons-round',
  'material-icons-sharp',
  'material-symbols-outlined',
  'material-symbols-rounded',
  'material-symbols-sharp',
  'mdi-v7',
  'roboto-font',
  'roboto-font-latin-ext',
  'themify',
] as const

/** Modern language packs from quasar/lang/index.json. */
export const GENERATED_LANG_MODERN = [
  'ar',
  'ar-TN',
  'az-Latn',
  'bg',
  'bn',
  'bs-BA',
  'ca',
  'ckb',
  'cs',
  'da',
  'de',
  'de-CH',
  'de-DE',
  'el',
  'en-GB',
  'en-US',
  'eo',
  'es',
  'et',
  'eu',
  'fa',
  'fa-IR',
  'fi',
  'fr',
  'gn',
  'he',
  'hi',
  'hr',
  'hu',
  'id',
  'is',
  'it',
  'ja',
  'kk',
  'km',
  'ko-KR',
  'lb',
  'lt',
  'lu',
  'lv',
  'mk',
  'ml',
  'ms',
  'ms-MY',
  'my',
  'nb-NO',
  'nl',
  'pl',
  'pt',
  'pt-BR',
  'ro',
  'ru',
  'sk',
  'sl',
  'sm',
  'sq',
  'sr',
  'sr-Cyrl',
  'sv',
  'ta',
  'th',
  'tl',
  'tr',
  'ug',
  'uk',
  'ur-PK',
  'uz-Cyrl',
  'uz-Latn',
  'vi',
  'zh-CN',
  'zh-TW',
] as const

/** quasar/lang/*.js files absent from index.json (deprecated aliases). */
export const GENERATED_LANG_ALIAS_FILES = [
  'kur-CKB',
  'mm',
  'sr-CYR',
] as const

/** Every quasar/dist/api entry with type plugin. */
export const GENERATED_QUASAR_PLUGINS = [
  'AddressbarColor',
  'AppFullscreen',
  'AppVisibility',
  'BottomSheet',
  'Brand',
  'Cookies',
  'Dark',
  'Dialog',
  'IconSet',
  'Lang',
  'Loading',
  'LoadingBar',
  'LocalStorage',
  'Meta',
  'Notify',
  'Platform',
  'Screen',
  'SessionStorage',
] as const

export const GENERATED_QUASAR_VERSION = '2.27.0' as const

export const GENERATED_QUASAR_EXTRAS_VERSION = '2.0.4' as const
